# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-29 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gruh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nachni', models.IntegerField(default=0)),
                ('mari', models.IntegerField(default=0)),
                ('oat', models.IntegerField(default=0)),
            ],
        ),
    ]
