# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-29 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_gruh'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sakhi',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
