# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-29 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='urgent_status',
            field=models.IntegerField(default=-1),
        ),
    ]
