# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-29 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_urgent_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='urgent_status',
            new_name='urgent',
        ),
    ]
