# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-29 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170729_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sakhi_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('distance', models.IntegerField(default=5000000)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='placed_from',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
