# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-29 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170729_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='customer_addr',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distance',
            name='sakhi_addr',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
