# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-29 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170729_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_direction',
            field=models.IntegerField(default=-1),
        ),
    ]
