# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-29 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_order_order_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='customer_lat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='distance',
            name='customer_lng',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='distance',
            name='sakhi_lat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='distance',
            name='sakhi_lng',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
